FROM alpine:latest

# 编写者
LABEL maintainer="lbc346093@163.com"

ENV LANG=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8

ENV TZ=Asia/Shanghai


RUN apk update && apk add --no-cache bash curl vim unzip tzdata && \
ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
echo "Asia/Shanghai" > /etc/timezone


# 切换默认 shell 为 bash
SHELL ["/bin/bash", "-c"]

WORKDIR /