# 基础镜像
FROM php:5.6-fpm-alpine

# 编写者
LABEL maintainer="lbc346093@163.com"

ENV LANG C.UTF-8
ENV TZ Asia/Shanghai

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories && apk update \

    # 系统时区设置
    && apk add --no-cache tzdata && ln -sf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ >> /etc/timezone \

    # 安装常用系统服务
    && apk add --no-cache wget vim gcc g++ automake autoconf make openssl-dev \

    # 安装bash支持
    && apk add --no-cache bash bash-doc bash-completion && sed -i 's/ash/bash/g' /etc/passwd \

    # 别名和环境设置
    && echo -e 'export HISTTIMEFORMAT="%Y-%m-%d %H:%M:%S "\n \
                export PS1="[\u@\h \W]# "\n \
                alias wget="wget -U"\n \
                alias ll="ls -alF"\n \
                alias ls="ls --color=auto"\n \
                source /etc/profile.d/bash_completion.sh\n' >> /root/.bashrc \

    # composer
    && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin/ --filename=composer \

    # php.ini
    && mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini" \

    # PHP.INI修改
    && sed -i "s#;date.timezone =#date.timezone = $TZ#g" $PHP_INI_DIR/php.ini \
    && sed -i "s#display_errors = Off#display_errors = On#g" $PHP_INI_DIR/php.ini \
    && sed -i "s#error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT#error_reporting = E_ERROR | E_WARNING | E_PARSE#g" $PHP_INI_DIR/php.ini \
    && sed -i "s#upload_max_filesize = 2M#upload_max_filesize = 100M#g" $PHP_INI_DIR/php.ini \
    && sed -i "s#post_max_size = 8M#post_max_size = 100M#g" $PHP_INI_DIR/php.ini \
    && sed -i "s#memory_limit = 128M#memory_limit = 512M#g" $PHP_INI_DIR/php.ini \

    # 安装php依赖的系统服务
    && apk add --no-cache libmcrypt-dev freetype-dev libjpeg-turbo-dev libpng-dev \

    # 安装php扩展
    && docker-php-ext-install mcrypt bcmath zip mbstring mysqli pdo pdo_mysql mysql \

    # pecl安装
    && pecl install redis-3.1.6 && docker-php-ext-enable redis \


    # 放在最后，删除安装文件
    && docker-php-source delete \

    # 删除无用的文件，使镜像文件足够小
    && rm -rf /var/cache/apk/* && rm -rf /root/.cache && rm -rf /tmp/*

CMD ["php-fpm"]

WORKDIR /