# 基础镜像
FROM php:5.6-fpm-alpine

# 编写者
LABEL maintainer="lbc346093@163.com"

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories && apk update \

    # 安装bash支持
    && apk add --no-cache bash bash-doc bash-completion && sed -i 's/ash/bash/g' /etc/passwd \

    # 安装常用系统服务
    && apk add --no-cache wget vim gcc g++ automake autoconf make openssl-dev \

    # bash和系统别名设置
    && echo -e 'export HISTTIMEFORMAT="%Y-%m-%d %H:%M:%S "\n \
                export PS1="[\u@\h \W]# "\n \
                alias wget="wget -U"\n \
                alias ll="ls -alF"\n \
                alias ls="ls --color=auto"\n \
                source /etc/profile.d/bash_completion.sh\n' >> /root/.bashrc \

    # composer
    && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin/ --filename=composer \

    # php.ini
    && cp -rf "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini" \

    # 安装php依赖的系统服务
    && apk add --no-cache libmcrypt-dev freetype-dev libjpeg-turbo-dev libpng-dev \

    # 安装php扩展
    && docker-php-ext-install mcrypt bcmath zip mbstring mysqli pdo pdo_mysql mysql \

    # pecl安装
    && pecl install redis-3.1.6 && docker-php-ext-enable redis

CMD ["php-fpm"]

WORKDIR /