# 基础镜像
FROM centos:7

# 编写者
LABEL maintainer="lbc346093@163.com"

# 拷贝必要文件
COPY service/php.service /lib/systemd/system/
ADD resource/php7/php*.tar.* /tmp

# php安装目录
ARG install_path
# 系统包   如vim、lrzsz等
ARG extra_packages=vim

RUN yum install -y wget $extra_packages \
    # 时区设置
    && ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && echo "Asia/Shanghai" >> /etc/timezone \
	# 切换镜像源
	&& cd /etc/yum.repos.d \
	&& wget http://mirrors.aliyun.com/repo/Centos-7.repo https://mirrors.aliyun.com/repo/epel-7.repo \
	&& mv Centos-7.repo CentOS-Base.repo && yum clean all  &&  yum makecache \
	# 安装基于系统的一些依赖
    && yum install -y gcc gcc-c++ glibc make autoconf openssl openssl-devel libxslt-devel gd gd-devel \
    pcre pcre-devel epel-release \
	# 创建用户
	&& useradd -M -s /sbin/nologin www \
	# 安装php的一系列依赖包
	&& yum -y install epel-release \
	&& yum -y install libmcrypt-devel \
	&& yum -y install libxml2 libxml2-devel openssl openssl-devel \
	curl-devel libjpeg-devel libpng-devel freetype-devel libicu-devel gettext-devel \
	# 编译安装
	&& cd /tmp && cp -r php-* php && cd php && ./configure \
    --prefix=$install_path \
	--with-config-file-path=$install_path/etc \
	--with-fpm-user=www \
	--with-fpm-group=www \
	--with-iconv-dir \
	--with-freetype-dir \
	--with-jpeg-dir \
	--with-png-dir \
	--with-zlib \
	--with-libxml-dir \
	--with-pear \
	--with-gettext \
	--with-curl \
	--with-xmlrpc \
	--with-openssl \
	--with-mhash \
	--with-gd \
	--with-mysqli=mysqlnd \
	--with-pdo-mysql=mysqlnd \
	--enable-mysqlnd \
	--enable-mysqlnd-compression-support \
	--enable-fpm \
	--enable-xml \
	--enable-rpath \
	--enable-bcmath \
	--enable-shmop \
	--enable-sysvsem \
	--enable-inline-optimization \
	--enable-mbregex \
	--enable-mbstring \
	--enable-intl \
	--enable-ftp \
	--enable-gd-jis-conv \
	--enable-pcntl \
	--enable-sockets \
	--enable-soap \
	--enable-fileinfo \
	--enable-opcache \
	--enable-maintainer-zts \
	&& make && make install \
	# 拷贝相关配置文件
	&& cp php.ini-production $install_path/etc/php.ini \
	&& cp $install_path/etc/php-fpm.conf.default $install_path/etc/php-fpm.conf \
	&& cp $install_path/etc/php-fpm.d/www.conf.default $install_path/etc/php-fpm.d/www.conf \
	# 开机自启
	&& systemctl enable php.service \
	# 环境变量设置
	&& echo 'export PATH=$PATH':"$install_path/bin" >> /etc/bashrc \
	&& source /etc/bashrc \
	# composer安装
	&& curl -sS https://getcomposer.org/installer | php \
	&& mv composer.phar /usr/local/bin/composer \
	&& yum install -y zip unzip \
	# 删除无用的文件，使镜像文件足够小
	&& yum clean all && rm -rf /tmp/*

WORKDIR /