# 基础镜像
FROM centos:7

# 编写者
LABEL maintainer="lbc346093@163.com"

# 系统包   如vim、lrzsz等
ARG extra_packages=vim

# 系统代理
ARG proxy=socks5://docker.for.mac.host.internal:1087

RUN yum install -y wget $extra_packages \
    # 时区设置
    && ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && echo "Asia/Shanghai" >> /etc/timezone \
    # 切换镜像源
    && cd /etc/yum.repos.d \
    && wget http://mirrors.aliyun.com/repo/Centos-7.repo https://mirrors.aliyun.com/repo/epel-7.repo \
    && mv Centos-7.repo CentOS-Base.repo && yum clean all  &&  yum makecache \
    # 安装基于系统的一些依赖
    && yum install -y gcc gcc-c++ glibc make autoconf openssl openssl-devel libxslt-devel gd gd-devel \
        pcre pcre-devel epel-release \

    # 系统代理设置
    && echo -e "alias setProxy=\"export ALL_PROXY=$proxy; echo -e '已开启代理'\" \nalias unsetProxy=\"unset ALL_PROXY; echo -e '已关闭代理'\" \nalias ip=\"curl cip.cc\" \nalias wget=\"wget -U\" \n"  >> /etc/bashrc \

	# 删除无用的文件，使镜像文件足够小
	&& yum clean all && rm -rf /tmp/*

WORKDIR /