# 基础镜像
FROM alpine

# 编写者
LABEL maintainer="lbc346093@163.com"

ENV LANG C.UTF-8
ENV TZ Asia/Shanghai

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories && apk update \

    # 系统时区设置
    && apk add --no-cache tzdata && ln -sf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ >> /etc/timezone \

    # 安装常用系统服务
    && apk add --no-cache wget vim gcc g++ automake autoconf make openssl-dev \

    # 安装bash支持
    && apk add --no-cache bash bash-doc bash-completion && sed -i 's/ash/bash/g' /etc/passwd \

    # 别名和环境设置
    && echo -e 'export HISTTIMEFORMAT="%Y-%m-%d %H:%M:%S "\n \
                export PS1="[\u@\h \W]# "\n \
                alias wget="wget -U"\n \
                alias ll="ls -alF"\n \
                alias ls="ls --color=auto"\n \
                source /etc/profile.d/bash_completion.sh\n' >> /root/.bashrc \

	# 删除无用的文件，使镜像文件足够小
	&& rm -rf /var/cache/apk/* && rm -rf /root/.cache && rm -rf /tmp/*

CMD ["/bin/bash"]

WORKDIR /