version: '3'

#设置默认虚拟网桥
networks:
  default:
    name: network-common
    external: true

services:

  canal:
    image: canal/canal-server:latest
    container_name: canal
    ports:
      - "11110:11110"
      - "11111:11111"
      - "11112:11112"
      - "9100:9100"
    env_file: ../../env/canal/example.instance.properties
    environment:
      TZ: "Asia/Shanghai"
    privileged: true
    restart: unless-stopped
    stdin_open: true
    tty: true