version: '3'

#设置默认虚拟网桥
networks:
  default:
    external:
      name: network-commom

services:

  canal:
    image: alpine
    build:
      context: ../../
      dockerfile: dockerfile-alpine
    container_name: canal
    ports:
      - "19991-19999:19991-19999"
    environment:
      TZ: "Asia/Shanghai"
    privileged: true
    restart: unless-stopped
    stdin_open: true
    tty: true