version: '3'

#设置默认虚拟网桥
networks:
  default:
    external:
      name: network-commom

services:

  canal:
    image: canal/canal-server:latest
    container_name: canal
    ports:
      - "11110:11110"
      - "11111:11111"
      - "11112:11112"
      - "9100:9100"
    env_file: ../../env/canal/oemsaas.env
    environment:
      TZ: $cana
    privileged: true
    restart: unless-stopped
    stdin_open: true
    tty: true