version: '3'

#设置默认虚拟网桥
networks:
  default:
    name: network-common
    external: true

services:

  socat:
    image: ilanyu/golang-reverseproxy
    container_name: jrebel-activation
    ports:
      - "8888:8888"
    restart: unless-stopped