version: '3'

#设置默认虚拟网桥
networks:
  default:
    name: network-common
    external: true

services:

  socat:
    image: alpine/socat
    container_name: socat
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "2375:2375"
    command: "tcp-listen:2375,fork,reuseaddr unix-connect:/var/run/docker.sock"
    restart: unless-stopped