version: '3'

#设置默认虚拟网桥
networks:
  default:
    external:
      name: network-commom

services:

  nginx:
    image: nginx:alpine
    container_name: nginx
    #    networks:
    #      devnet:
    ports:
      - "80:80"
    volumes:
      - "D:/docker-develop-env/env/nginx/conf:/etc/nginx"
#      - "D:/docker-develop-env/env/nginx/logs:/var/log/nginx"
      - "D:/projects:/home/wwwroot"
    environment:
      TZ: "Asia/Shanghai"
    depends_on:
      - "php73"
    restart: unless-stopped

  httpd:
    image: httpd:alpine
    container_name: httpd
    ports:
      - "8080:8080"
    volumes:
      - "D:/docker-develop-env/env/apache2/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf"
      - "D:/docker-develop-env/env/apache2/conf/vhosts:/usr/local/apache2/conf/vhosts"
      - "D:/projects:/home/wwwroot"
    environment:
      TZ: "Asia/Shanghai"
    restart: unless-stopped

  php56:
    image: php56:v1
    build:
      context: ../
      dockerfile: dockerfile-php56
      args:
        install_path: "/usr/local/php"
        extra_packages: "vim lrzsz git"
    container_name: php56
    expose:
      - "9000"
    volumes:
      - "D:/projects:/home/wwwroot"
    environment:
      TZ: "Asia/Shanghai"
    command:
      - /usr/sbin/init
    privileged: true
    restart: unless-stopped

  php73:
    image: php73:v1
    build:
      context: ../
      dockerfile: dockerfile-php73
      args:
        install_path: "/usr/local/php"
        extra_packages: "vim lrzsz git"
    container_name: "php73"
    expose:
      - "9000"
    volumes:
      - "D:/projects:/home/wwwroot"
    environment:
      TZ: "Asia/Shanghai"
    command:
      - /usr/sbin/init
    privileged: true
    restart: unless-stopped

  mysql:
    container_name: mysql
    image: "mysql:5.6"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_ROOT_HOST: "%"
      TZ: "Asia/Shanghai"
    volumes:
      - "D:/docker-develop-env/env/mysql/data:/var/lib/mysql"
      - "D:/docker-develop-env/env/mysql/conf:/etc/mysql/conf.d"
    ports:
      - "3306:3306"
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - "D:/docker-develop-env/env/redis/config:/etc/redis/config"
      - "D:/docker-develop-env/env/redis/data:/data"
    environment:
      TZ: "Asia/Shanghai"
    command: redis-server /etc/redis/config/redis.conf


  #编译安装
#  nginx:
#    image: nginx:v1
#    build:
#      context: ../
#      dockerfile: dockerfile-nginx
#      args:
#        install_path: /usr/local/nginx
#        extra_package: vim lrzsz
#    container_name: nginx
#    ports:
#      - "80:80"
#      - "9990-9999:9990-9999"
#    volumes:
#      - "D:/projects:/home/wwwroot"
#    depends_on:
#      - "php73"
#    environment:
#      TZ: "Asia/Shanghai"
#    command:
#      - /usr/sbin/init
#    privileged: true
#    restart: unless-stopped


#  centos:
#    image: centos:7
#    container_name: centos
#    environment:
#      TZ: "Asia/Shanghai"
#    command:
#      - /usr/sbin/init
#    privileged: true
#    restart: unless-stopped
