version: '3'

#设置默认虚拟网桥
networks:
  default:
    external:
      name: network-commom

services:
  kibana:
    image: kibana:7.1.1
    container_name: kibana
    environment:
      - I18N_LOCALE=zh-CN
      - XPACK_GRAPH_ENABLED=true
      - TIMELION_ENABLED=true
      - XPACK_MONITORING_COLLECTION_ENABLED="true"
      - TZ="Asia/Shanghai"
      - ELASTICSEARCH_URL=http://es01:9200
      - ELASTICSEARCH_HOSTS=http://es01:9200
    ports:
      - 5601:5601

  elasticsearch1:
    image: elasticsearch:7.1.1
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02
      - cluster.initial_master_nodes=es01,es02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - TZ="Asia/Shanghai"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200

  elasticsearch2:
    image: elasticsearch:7.1.1
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01,es02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - TZ="Asia/Shanghai"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    expose:
      - "9300"
