version: '3'

#设置默认虚拟网桥
networks:
  default:
    external:
      name: network-commom

services:

  httpd:
    image: httpd:alpine
    container_name: httpd
    ports:
      - "8080:8080"
    volumes:
      - "/Users/liangbincheng/docker-develop-env/env/apache2/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf"
      - "/Users/liangbincheng/docker-develop-env/env/apache2/conf/vhosts:/usr/local/apache2/conf/vhosts"
      - "/Users/liangbincheng/projects:/home/wwwroot"
    environment:
      TZ: "Asia/Shanghai"
    restart: unless-stopped