version: '3'

#设置默认虚拟网桥
networks:
  default:
    name: network-common
    external: true

services:

  httpd:
    image: httpd:alpine
    container_name: httpd
    ports:
      - "8080:8080"
    volumes:
      - "../../env/apache2/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf"
      - "../../env/apache2/conf/vhosts:/usr/local/apache2/conf/vhosts"
      - "/Users/liangbincheng/shopyy:/home/wwwroot"
    environment:
      TZ: "Asia/Shanghai"
    restart: unless-stopped