version: '3'

#设置默认虚拟网桥
networks:
  default:
    name: network-common
    external: true

services:

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - "../../env/nginx/conf:/etc/nginx"
      - "/Users/liangbincheng/oemsaas:/home/wwwroot"
    environment:
      TZ: "Asia/Shanghai"
    restart: unless-stopped