version: '3'

#设置默认虚拟网桥
networks:
  default:
    external:
      name: network-commom

services:

  php56:
    image: php:v5.6
    build:
      context: ../../
      dockerfile: dockerfile-php56
      args:
        install_path: "/usr/local/php"
        extra_packages: "vim lrzsz git"
        proxy: "socks5://docker.for.mac.host.internal:1087"
    container_name: php56
    expose:
      - "9000"
    volumes:
      - "/Users/liangbincheng/projects:/home/wwwroot"
    environment:
      TZ: "Asia/Shanghai"
    command:
      - /usr/sbin/init
    privileged: true
    restart: unless-stopped