version: '3'

#设置默认虚拟网桥
networks:
  default:
    external:
      name: network-commom

services:

  php56:
    image: php:v5.6
    build:
      context: ../../
      dockerfile: dockerfile-php56
    container_name: php56
    expose:
      - "9000"
    volumes:
      - "/Users/liangbincheng/projects:/home/wwwroot"
    environment:
      TZ: "Asia/Shanghai"
    privileged: true
    restart: unless-stopped
    stdin_open: true
    tty: true