version: '3'

#设置默认虚拟网桥
networks:
  default:
    external:
      name: network-common

services:

  php73:
    image: php:v7.3
    build:
      context: ../../
      dockerfile: dockerfile-php73
    container_name: php73
    expose:
      - "9000"
    volumes:
      - "/Users/liangbincheng/oemsass:/home/wwwroot"
    environment:
      TZ: "Asia/Shanghai"
    privileged: true
    restart: unless-stopped
    stdin_open: true
    tty: true