version: '3'

#设置默认虚拟网桥
networks:
  default:
    external:
      name: network-commom

services:

  tabix:
    container_name: tabix
    image: spoonest/clickhouse-tabix-web-client
    environment:
      USER: "root"
      PASSWORD: "123456"
      TZ: "Asia/Shanghai"
    ports:
      - "19001:80"

    depends_on:
      - clickhouse

    restart: unless-stopped

  clickhouse:
    container_name: clickhouse
    image: yandex/clickhouse-server:21.3-alpine
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - "/Users/liangbincheng/docker-develop-env/env/clickhouse/data:/var/lib/clickhouse"
      - "/Users/liangbincheng/docker-develop-env/env/clickhouse/conf:/etc/clickhouse-server"
    expose:
      - "9000"
    ports:
      - "8123:8123"
      - "19000:9000"
    user: root

    restart: unless-stopped
