version: '3'

#设置默认虚拟网桥
networks:
  default:
    external:
      name: network-commom

services:
  kibana:
    image: kibana:7.4.0
    container_name: kibana
    environment:
      - I18N_LOCALE=zh-CN
      - XPACK_GRAPH_ENABLED=true
      - TIMELION_ENABLED=true
      - XPACK_MONITORING_COLLECTION_ENABLED="true"
      - ELASTICSEARCH_URL=http://es01:9200
      - ELASTICSEARCH_HOSTS=http://es01:9200
      - TZ="Asia/Shanghai"
    ports:
      - 5601:5601

  elasticsearch1:
    image: elasticsearch:7.4.0
    container_name: es01
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - TZ="Asia/Shanghai"
    volumes:
      - "../../env/elasticsearch/es01.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300

#  elasticsearch2:
#    image: elasticsearch:7.4.0
#    container_name: es02
#    environment:
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#      - TZ="Asia/Shanghai"
#    volumes:
#      - "../../env/elasticsearch/es02.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    expose:
#      - 9200
#      - 9300
