version: '3'

#设置默认虚拟网桥
networks:
  default:
    name: network-common
    external: true

services:

  mysql:
    container_name: mysql
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_ROOT_HOST: "%"
      TZ: "Asia/Shanghai"
    volumes:
      - "../../env/mysql/data:/var/lib/mysql"
      - "../../env/mysql/conf:/etc/mysql/conf.d"
    ports:
      - "3306:3306"
    restart: unless-stopped