version: '3'

#设置默认虚拟网桥
networks:
  default:
    name: network-common
    external: true

services:

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - "../../env/redis/config:/etc/redis/config"
      - "../../env/redis/data:/data"
    environment:
      TZ: "Asia/Shanghai"
    command: redis-server /etc/redis/config/redis.conf